### ISSUE TITLE
Why is vim better than PhpStorm the best text editor?

### ISSUE THREAD

**Issue by andrewhood125** [svpernova09/ama#2]
:heart: :tada:

**Comment by svpernova09** [comment]
Because when your server shits the bed you won't be able to run Phpstorm on it to fix your files :D

I learned vi/vim back in the "dark ages", when I was first learning linux ~1998/99. My mentor back then was very adamant about me learning vi/vim instead of anything else because "What else are you doing to use to fix your server when it fucks up?" That's still the same thing I tell people today that are getting into server administration.

However when it comes to text editors outside of the server world my advice is a bit different. Learn a text editor so well you know it's "gotchas" better than you know it's features. Then if you want to branch out, have at it. Learn the next editor the same way, till the wheels fall off. One of the big things that I see on social media and IRC channels are people berating one another for which editor they use. Don't let anyone tell you what to use *IF* what you're using is solving your problems. However be open to them showing you how *they* work because you will inevitably come across a tool or trick that you can adapt into your workflow.
