### ISSUE TITLE
Thoughts on the recent change to JetBrains licensing?

### ISSUE THREAD

**Issue by andrewhood125** [svpernova09/ama#3]

**Comment by svpernova09** [comment]
As someone who loves Phpstorm and uses Pycharm more and more I'm pretty excited about the changes. As a current user if I wanted to just stick with Phpstorm my price wouldn't change, I would just have to upgrade every year instead of when I wanted to. Some people take issue with that and I can certainly see their point.

I'm looking forward to the changes because I love being able to jump between Jetbrains products and the look and feel is consistent.

I think it's more hurtful to the hobbyists out there because they may not be able to justify the expense. I get that.

It sounds like there was a bunch of upheaval and that Jetbrains may be doing something to acknowledge that. Not sure.
