### ISSUE TITLE
What's your favorite project on GitHub?

### ISSUE THREAD

**Issue by sindresorhus** [svpernova09/ama#5]

**Comment by svpernova09** [comment]
[Laravel Homestead](https://github.com/laravel/homestead). It's a project that brings the awesome power of Vagrant for local development environments and makes it very developer friendly for those using the Laravel PHP framework. It's lowering the barrier of entry so that even new or novice developers can get a local virtual machine up and running with little effort.

**Comment by andrewhood125** [comment]
Representttttttttt.
